from tkinter import *
foablak=Tk()
def osszeg():
    r = int(Sugarmezo.get())
    m = int(Magasmezo.get())
    c = 3.14*r*r*m
    Terfogatmezo.delete(0, END)
    Terfogatmezo.insert(0, ' '+str(c))
    Fahenger.delete(0, END)
    Fahenger.insert(0 ' '+str(c)
def tomeg():
    Terfogat=(Terfogatmezo.get())
    tomeg=7800*Terfogatmezo
    Vashengermezo.delete(0, END)
    Vashengermezo.insert(0, ' '+str(tomeg)
def fatomeg():
    Terfogat=(Terfogatmezo.get())
    fatomeg=800*Terfogatmezo
    Fahengermezo.delete(0, END)
    Fahengermezo.insert(0, ' '+str(fatomeg)
Sugar=Label(foablak, text='Sugár (cm):')
Sugar.grid()
Sugarmezo=Entry(foablak)
Sugarmezo.grid()
Magassag=Label(foablak, text='Magasság (cm):')
Magassag.grid()
Magasmezo=Entry(foablak)
Magasmezo.grid()
Kiszámít=Button(foablak, text='Kiszámít', command=osszeg)
Kiszámít.grid()
Terfogat=Label(foablak, text='Térfogat:')
Terfogat.grid()
Terfogatmezo=Entry(foablak)
Terfogatmezo.grid()
Vashenger=Label(foablak, text='Vashenger')
Vashenger.grid()
Vashengermezo=Entry(foablak)
Vashengermezo.grid()
Fahenger=Label(foablak, text='Fahenger')
Fahenger.grid()
Fahengermezo=Entry(foablak)
Fahengermezo.grid()
foablak.mainloop()
